### ISSUE TITLE
运行报错  请问一下 这是什么原因呢？

### ISSUE THREAD

**Issue by yuhe520521** [howie6879/importData#1]
Traceback (most recent call last):
  File "saveSql.py", line 14, in <module>
    cli()
  File "saveSql.py", line 7, in cli
    kwargs = docopt(__doc__)
  File "/usr/local/lib/python2.7/site-packages/docopt.py", line 558, in docopt
    DocoptExit.usage = printable_usage(doc)
  File "/usr/local/lib/python2.7/site-packages/docopt.py", line 466, in printable_usage
    usage_split = re.split(r'([Uu][Ss][Aa][Gg][Ee]:)', doc)
  File "/usr/local/Cellar/python/2.7.14_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 171, in split
    return _compile(pattern, flags).split(string, maxsplit)
TypeError: expected string or buffer

我打印出 __doc__  是none  请问作者有遇到过这个问题么？

**Comment by howie6879** [comment]
可能是你输入的原因吧 造成docopt 报错 你可以直接运行下insertData.py

**Comment by yuhe520521** [comment]
非常感谢您的 回答  我已经解决 是因为我把 注释文档改了 导致 docopt  有了问题
已经开始导入了 但是又报了个错 好像是说编码问题  是不是 我的excel 里面的编码出了问题？
Traceback (most recent call last):
  File "saveSql.py", line 28, in <module>
    cli()
  File "saveSql.py", line 22, in cli
    insertData(**kwargs)
  File "/Users/yichaozhao/Downloads/gitTestDemo/importData/insertData.py", line 31, in __init__
    self.judge(self.verFile(allStyle))
  File "/Users/yichaozhao/Downloads/gitTestDemo/importData/insertData.py", line 50, in judge
    self.saveExcel(file)
  File "/Users/yichaozhao/Downloads/gitTestDemo/importData/insertData.py", line 62, in saveExcel
    self.saveData(df)
  File "/Users/yichaozhao/Downloads/gitTestDemo/importData/insertData.py", line 71, in saveData
    row = ','.join(list(map(lambda x: self.db.conn.escape(str(x).strip()), df.values[num])))
  File "/Users/yichaozhao/Downloads/gitTestDemo/importData/insertData.py", line 71, in <lambda>
    row = ','.join(list(map(lambda x: self.db.conn.escape(str(x).strip()), df.values[num])))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

**Comment by yuhe520521** [comment]
我再 savesql.py 的开头加了  
# -*-coding:utf-8-*-
如果不加 会报错
File "saveSql.py", line 7
SyntaxError: Non-ASCII character '\xe6' in file saveSql.py on line 8, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by howie6879** [comment]
那就行
